### ISSUE TITLE
window dimensions

### ISSUE THREAD

**Issue by joernroeder** [Milchreis/UiBooster#10]
I'm using the processing version. is there any way to specify the window/form dimensions?

**Comment by Milchreis** [comment]
Hi @joernroeder 

currently there is no special method to easily change the window size, but it's possible in that way:
````java
FilledForm form = new UiBooster().createForm().addLabel("Hello").run();
form.getWindow().setSize(800, 600);
````

**Comment by joernroeder** [comment]
@Milchreis thanks! this works perfectly!
