### ISSUE TITLE
Errors, warnings and info dialogs appear behind forms

### ISSUE THREAD

**Issue by nicholasveronico** [Milchreis/UiBooster#121]
Hi there,

When an existing form is open and an error, info or warning dialog is opened (for example, as a result of an input listener within the form), the blocking dialog appears behind the form, resulting in the user moving the form out of the way to press "Ok" to unblock execution.

**Comment by Milchreis** [comment]
Hi Nicholas,

thank you for your contribution 😊. I will check it out on the weekend and possible merge the PR in the main branch.
Have a nice day.

Nick
