### ISSUE TITLE
Maven Artifact is broken

### ISSUE THREAD

**Issue by leonitousconforti** [Milchreis/UiBooster#19]
Just a heads up, the maven artifact is broken. 

The cause of this has nothing to do with your code but rather that one of the dependencies, [Darcula](https://github.com/bulenkov/Darcula), is hosted on [spring.io](https://spring.io/) and spring has recently implemented some permission changes as stated in [this-Notice of Permissions Changes to repo.spring.io, Fall and Winter, 2020-](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020) article.

Everything works fine if you get Darcula from source and build UiBooster from source using that

**Comment by leonitousconforti** [comment]
It looks like Darcula can be found on the bintray and maven repositories now

https://bintray.com/lkishalmi/maven/com.bulenkov.darcula
https://mvnrepository.com/artifact/com.bulenkov/darcula

**Comment by leonitousconforti** [comment]
Here is the exact error for others
....................................................

[ERROR] Failed to execute goal on project: Could not resolve dependencies for project

Failed to collect dependencies at com.github.Milchreis:UiBooster:jar:1.9.0 -> com.bulenkov:darcula:jar:2018.2: Failed to read artifact descriptor for com.bulenkov:darcula:jar:2018.2

Could not transfer artifact com.bulenkov:darcula:pom:2018.2 from/to spring (https://repo.spring.io/plugins-release/): Authentication failed for https://repo.spring.io/plugins-release/com/bulenkov/darcula/2018.2/darcula-2018.2.pom 401 Unauthorized

**Comment by Milchreis** [comment]
Hi @leonitousconforti 

thank you for report and PR. What do you think to of this repo for darcula:
https://github.com/ice1k/darcula

It‘s build and hosted on JitPack and the sources are accessible.

**Comment by leonitousconforti** [comment]
Looks like a better option to me, especially since it is open source! I have gone ahead and switched it
