### ISSUE TITLE
Release of new features

### ISSUE THREAD

**Issue by joernroeder** [Milchreis/UiBooster#30]
Hey @Milchreis, do you have any release schedule for the recently integrated features? I'm currently struggling with textarea rows in my processing project and have seen that this landed a couple of commits ago. Any change this gets relased soonish?

**Comment by Milchreis** [comment]
hi @joernroeder,

until now I was not aware that anyone expects the new features. Therefore, I just collected and not yet published. But I can gladly release version 1.10.0 in the next few days.

**Comment by Milchreis** [comment]
Release 1.10.0 is out now

**Comment by joernroeder** [comment]
@Milchreis Thank you! 🚀
