### ISSUE TITLE
Support for other Look & Feels

### ISSUE THREAD

**Issue by xDUDSSx** [Milchreis/UiBooster#31]
Hello,
I was wondering if there is any way to use the currently installed look and feel for the dialog components. I haven't looked at the code but I understand there are 3 themes to pick from using the UIBoosterOptions. I presume the library must be installing specific UIs for individual dialog components or something. 

Anyway, wouldn't it be possible to just let the components use the currently installed "global" look and feel and UIs currently installed? I'd say that would make this library a lot more useful since it's important that the application and dialog look and feels match.

**Comment by Milchreis** [comment]
Hi xDUDSSx,

it's a good point. I will consider it for the next release. Thank you for the idea ☺
