### ISSUE TITLE
Form differentiation between OK and X for exit

### ISSUE THREAD

**Issue by KotzaBoss** [Milchreis/UiBooster#37]
Is it possible to know after a Form has been filled whether the user clicked OK or the X button?

The Form seems perfect for what im trying to make which is a Recipe app for an university assignment. However its important to know  whether the user accepted or denied the form and i dont think its something i can deduce from the values alone for example what if 90% through filling in the fields he chooses to cancel.

**Comment by Milchreis** [comment]
hi @KotzaBoss 

you are right. Currently the form doesn't support this feature, but it is very useful. So I will implement this feature in the next days.

**Comment by KotzaBoss** [comment]
Excuse my ignorance but is gradle going to pick up on the changes automatically? or must i do a manual "refresh"

**Comment by Milchreis** [comment]
Gradle uses the current version 1.11.0 of UiBooster. Your feature will be released with verison 1.12.0. I have to do some tests before I deploy the next version. I hope you could be patient for the next week :-)

If you need the feature very quickly, you could clone the master of this repo and build the library for your self

**Comment by KotzaBoss** [comment]
Ok, there is no rush. Its just a throwaway uni assignment which in overdoing anyway.
Thank you for considering my issue!
