### ISSUE TITLE
SelectionFormElement ability to replace possibilities

### ISSUE THREAD

**Issue by sgjava** [Milchreis/UiBooster#56]
Consider the ability to replace the possibilities list in SelectionFormElement. For instance I'll refresh data into a new list and want to replace it.

**Comment by sgjava** [comment]
I just added accessor and mutator to SelectionFormElement for possibilities.

**Comment by sgjava** [comment]
I added the following to SelectionFormElement (you might have a better idea):

```
    public List<String> getPossibilities() {
        return possibilities;
    }

    public void setPossibilities(List<String> possibilities) {
        this.possibilities = possibilities;
        box.setModel(new DefaultComboBoxModel<String>(possibilities.toArray(new String[0])));
        box.setSelectedItem(possibilities.get(0));
    }
```

**Comment by Milchreis** [comment]
hi @sgjava 

thank you for your feedback. If you want to change code feel free to create pull requests. It's much more easy to you an me 😊
I added your suggestion with some small changes and a test case. I hope it works for you.

**Comment by sgjava** [comment]
Yep, I can do PRs.
