### ISSUE TITLE
'showTable​' question.

### ISSUE THREAD

**Issue by SeongJongKwak** [Milchreis/UiBooster#64]
1. ref url : https://milchreis.github.io/uibooster-for-processing/reference/uibooster/components/TableDialog.html
2. ref url2 : https://github.com/Milchreis/uibooster-for-processing

1) Package uibooster > Class UiBooster > showTable​

```
String[][] modifiedData = new UiBooster().showTable(    // showTableImmutable for immutable tables
        new String[][]{
                {"Jimmy Johnson", "35", "Zombieland"},
                {"Danny Durango", "23", "Hangover"},
                {"Larry Berry", "54", ""}
        },
        Arrays.asList("Name", "Age", "Favorite movie"),
        "Favorite movies");

```
2) Package uibooster.components > Class TableDialog >  showTable​

`static java.lang.String[][]	showTable​(java.lang.String[][] data, java.util.List<java.lang.String> header, java.lang.String title, java.lang.String iconPath, boolean isEditable)`

```
String[][] modifiedData = new UiBooster().showTable(    // showTableImmutable for immutable tables
        new String[][]{
                {"Jimmy Johnson", "35", "Zombieland"},
                {"Danny Durango", "23", "Hangover"},
                {"Larry Berry", "54", ""}
        },
        Arrays.asList("Name", "Age", "Favorite movie"),
        "Favorite movies","icon.png",false);
```

The above source code does not work. Why?

**Comment by Milchreis** [comment]
hi @SeongJongKwak 

the method signature from your second snippit is not supported. The method `UiBooster.showTable()` expects only 3 arguments: 

1. data as 2d string array
2. header as string list or array
3. title as string

You used the method signature from `TableDialog.showTable()` but not the method it self. Moreover it's not recommended to use the internal classes, because for some refactorings it could have a different name later on.

If you want to change the icon, you have to use the UiBooster options:

```java
new UiBooster(UiBoosterOptions.Theme.DARK_THEME, "/path/to/your/custom-window-icon.png").showTable(/*...*/);
```

**Comment by SeongJongKwak** [comment]
@Milchreis 

1. Thank you very much for your kind reply.
2. 'Icon' change or 'Theme change' works well because you let me know.

thank you. Finally,
`Arrays.asList("Name", "Age", "Favorite movie"),  "Favorite movies","icon.png",false);`
false - how to disable modification.

Is there a way to prevent it from being edited? The boolean over there seems to tell you if it's fixed or not. please check.
Any help would be appreciated.

**Comment by Milchreis** [comment]
Ah ok, you want to prevent changes by the user. I thougth the question points out to the icon-parameter.
You can use `UiBooster.showTableImmutable()` to create uneditable tables. The method signature is the same as `showTable()`

**Comment by SeongJongKwak** [comment]
@Milchreis 

Thank you. Very thank you.

**Comment by Milchreis** [comment]
You are welcome! I am happy to help you. 😊
