### ISSUE TITLE
I am an idiot nube to java

### ISSUE THREAD

**Issue by GregSchofield** [Milchreis/UiBooster#81]
I would like to use _UiBooster_ for some simple projects, one of which is to learn JS, but I cannot install it. Have I missed the instructions or could you add some for a Linux user.

I mentioned _UiBooster_ in [Zettlr Markdown editor](https://github.com/Zettlr/Zettlr/discussions) discussion. Might be worth thinking about it as a master plugin accessory, a gui to make plugins.

Best of luck.

**Comment by Milchreis** [comment]
Hi Greg,

thank you for your interest in UiBooster 😊. 
UiBooster is not a standalone software, it is a library that can be used in other Java projects to program graphical user interfaces in few lines of code. To use UiBooster you have to add this library to your project (manually via classpath or as dependency in maven or gradle), this is platform independent and works on Linux too.

I don't know Zettlr, but it seems to be a pure JS/TS project, which might not be suitable for Java. But this decision should be made by the Zettlr team 😊 Anyway, thanks for the mention 👍.
